WAFFEN_DATEN = {
    'Keule': {'schaden': '1d4', 'schadenstyp': 'wucht', 'eigenschaften': ['leicht']},
    'Dolch': {'schaden': '1d4', 'schadenstyp': 'stich', 'eigenschaften': ['finesse', 'leicht', 'wurfwaffe']},
    'Großer Knüppel': {'schaden': '1d8', 'schadenstyp': 'wucht', 'eigenschaften': ['zweihändig']},
    'Handaxt': {'schaden': '1d6', 'schadenstyp': 'hieb', 'eigenschaften': ['leicht', 'wurfwaffe']},
    'Wurfspeer': {'schaden': '1d6', 'schadenstyp': 'stich', 'eigenschaften': ['wurfwaffe']},
    'Leichter Hammer': {'schaden': '1d4', 'schadenstyp': 'wucht', 'eigenschaften': ['leicht', 'wurfwaffe']},
    'Streitkolben': {'schaden': '1d6', 'schadenstyp': 'wucht', 'eigenschaften': []},
    'Kampfstab': {'schaden': '1d6', 'schadenstyp': 'wucht', 'eigenschaften': ['vielseitig (1d8)']},
    'Sichel': {'schaden': '1d4', 'schadenstyp': 'hieb', 'eigenschaften': ['leicht']},
    'Speer': {'schaden': '1d6', 'schadenstyp': 'stich', 'eigenschaften': ['wurfwaffe', 'vielseitig (1d8)']},
    'Leichte Armbrust': {'schaden': '1d8', 'schadenstyp': 'stich', 'eigenschaften': ['munition', 'fernkampf', 'zweihändig']},
    'Kurzbogen': {'schaden': '1d6', 'schadenstyp': 'stich', 'eigenschaften': ['munition', 'fernkampf', 'zweihändig']},
    'Schleuder': {'schaden': '1d4', 'schadenstyp': 'wucht', 'eigenschaften': ['munition', 'fernkampf']},
    'Streitaxt': {'schaden': '1d8', 'schadenstyp': 'hieb', 'eigenschaften': ['vielseitig (1d10)']},
    'Flegel': {'schaden': '1d8', 'schadenstyp': 'wucht', 'eigenschaften': []},
    'Gleve': {'schaden': '1d10', 'schadenstyp': 'hieb', 'eigenschaften': ['schwer', 'reichweite', 'zweihändig']},
    'Hellebarde': {'schaden': '1d10', 'schadenstyp': 'hieb', 'eigenschaften': ['schwer', 'reichweite', 'zweihändig']},
    'Großaxt': {'schaden': '1d12', 'schadenstyp': 'hieb', 'eigenschaften': ['schwer', 'zweihändig']},
    'Zweihänder': {'schaden': '2d6', 'schadenstyp': 'hieb', 'eigenschaften': ['schwer', 'zweihändig']},
    'Pike': {'schaden': '1d10', 'schadenstyp': 'stich', 'eigenschaften': ['schwer', 'reichweite', 'zweihändig']},
    'Kampfschwert': {'schaden': '1d8', 'schadenstyp': 'hieb', 'eigenschaften': ['vielseitig (1d10)']},
    'Langschwert': {'schaden': '1d8', 'schadenstyp': 'hieb', 'eigenschaften': ['vielseitig (1d10)']},
    'Morgenstern': {'schaden': '1d8', 'schadenstyp': 'stich', 'eigenschaften': []},
    'Rapier': {'schaden': '1d8', 'schadenstyp': 'stich', 'eigenschaften': ['finesse']},
    'Krummsäbel': {'schaden': '1d6', 'schadenstyp': 'hieb', 'eigenschaften': ['finesse', 'leicht']},
    'Kurzschwert': {'schaden': '1d6', 'schadenstyp': 'stich', 'eigenschaften': ['finesse', 'leicht']},
    'Kriegshammer': {'schaden': '1d8', 'schadenstyp': 'wucht', 'eigenschaften': ['vielseitig (1d10)']},
    'Peitsche': {'schaden': '1d4', 'schadenstyp': 'hieb', 'eigenschaften': ['finesse', 'reichweite']},
    'Handarmbrust': {'schaden': '1d6', 'schadenstyp': 'stich', 'eigenschaften': ['munition', 'fernkampf', 'leicht']},
    'Schwere Armbrust': {'schaden': '1d10', 'schadenstyp': 'stich', 'eigenschaften': ['munition', 'fernkampf', 'schwer', 'zweihändig']},
    'Langbogen': {'schaden': '1d8', 'schadenstyp': 'stich', 'eigenschaften': ['munition', 'fernkampf', 'schwer', 'zweihändig']},
}
