# Generated by Django 5.2.11 on 2026-02-26 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField(default=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='character_images/')),
                ('character_class', models.CharField(max_length=100)),
                ('subclass', models.CharField(blank=True, max_length=100)),
                ('race', models.CharField(max_length=100)),
                ('background', models.CharField(max_length=100)),
                ('alignment', models.CharField(max_length=50)),
                ('strength', models.IntegerField(default=10)),
                ('dexterity', models.IntegerField(default=10)),
                ('constitution', models.IntegerField(default=10)),
                ('intelligence', models.IntegerField(default=10)),
                ('wisdom', models.IntegerField(default=10)),
                ('charisma', models.IntegerField(default=10)),
                ('armor_class', models.IntegerField(default=10)),
                ('speed', models.IntegerField(default=30)),
                ('max_hp', models.IntegerField(default=10)),
                ('current_hp', models.IntegerField(default=10)),
                ('equipment', models.TextField(blank=True, help_text='Inventar')),
                ('gold', models.IntegerField(default=0)),
                ('personality_traits', models.TextField(blank=True)),
                ('ideals', models.TextField(blank=True)),
                ('bonds', models.TextField(blank=True)),
                ('flaws', models.TextField(blank=True)),
                ('backstory', models.TextField(blank=True)),
                ('appearance', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
