# Generated by Django 6.0.2 on 2026-02-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="copper",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="character",
            name="experience",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="character",
            name="hit_dice",
            field=models.CharField(default="1d10", max_length=20),
        ),
        migrations.AddField(
            model_name="character",
            name="hit_dice_total",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="character",
            name="inventory",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="character",
            name="max_experience",
            field=models.IntegerField(default=10000),
        ),
        migrations.AddField(
            model_name="character",
            name="proficiencies",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="character",
            name="silver",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="character",
            name="spell_slots",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="character",
            name="temp_hp",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="character",
            name="weapons",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
