# Generated by Django 5.2.11 on 2026-02-26 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_character_copper_character_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='available_stat_points',
            field=models.IntegerField(default=0),
        ),
    ]
