# Generated by Django 5.2.11 on 2026-03-02 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_character_available_stat_points'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['-level', 'name'], 'verbose_name': 'Charakter', 'verbose_name_plural': 'Charaktere'},
        ),
        migrations.AddField(
            model_name='character',
            name='feats',
            field=models.JSONField(blank=True, default=list, verbose_name='Talente'),
        ),
        migrations.AddField(
            model_name='character',
            name='features',
            field=models.JSONField(blank=True, default=list, verbose_name='Merkmale'),
        ),
        migrations.AddField(
            model_name='character',
            name='saving_throw_proficiencies',
            field=models.JSONField(blank=True, default=list, verbose_name='Rettungswurf-Übungen'),
        ),
        migrations.AddField(
            model_name='character',
            name='skill_expertises',
            field=models.JSONField(blank=True, default=list, verbose_name='Fertigkeits-Expertisen'),
        ),
        migrations.AddField(
            model_name='character',
            name='skill_proficiencies',
            field=models.JSONField(blank=True, default=list, verbose_name='Fertigkeits-Übungen'),
        ),
        migrations.AlterField(
            model_name='character',
            name='alignment',
            field=models.CharField(max_length=50, verbose_name='Gesinnung'),
        ),
        migrations.AlterField(
            model_name='character',
            name='appearance',
            field=models.TextField(blank=True, verbose_name='Aussehen'),
        ),
        migrations.AlterField(
            model_name='character',
            name='armor_class',
            field=models.IntegerField(default=10, verbose_name='Rüstungsklasse'),
        ),
        migrations.AlterField(
            model_name='character',
            name='available_stat_points',
            field=models.IntegerField(default=0, verbose_name='Verfügbare Attributspunkte'),
        ),
        migrations.AlterField(
            model_name='character',
            name='background',
            field=models.CharField(max_length=100, verbose_name='Hintergrund'),
        ),
        migrations.AlterField(
            model_name='character',
            name='backstory',
            field=models.TextField(blank=True, verbose_name='Hintergrundgeschichte'),
        ),
        migrations.AlterField(
            model_name='character',
            name='bonds',
            field=models.TextField(blank=True, verbose_name='Bindungen'),
        ),
        migrations.AlterField(
            model_name='character',
            name='character_class',
            field=models.CharField(max_length=100, verbose_name='Klasse'),
        ),
        migrations.AlterField(
            model_name='character',
            name='charisma',
            field=models.IntegerField(default=10, verbose_name='Charisma'),
        ),
        migrations.AlterField(
            model_name='character',
            name='constitution',
            field=models.IntegerField(default=10, verbose_name='Konstitution'),
        ),
        migrations.AlterField(
            model_name='character',
            name='copper',
            field=models.IntegerField(default=0, verbose_name='Kupfer'),
        ),
        migrations.AlterField(
            model_name='character',
            name='current_hp',
            field=models.IntegerField(default=10, verbose_name='Aktuelle Trefferpunkte'),
        ),
        migrations.AlterField(
            model_name='character',
            name='dexterity',
            field=models.IntegerField(default=10, verbose_name='Geschicklichkeit'),
        ),
        migrations.AlterField(
            model_name='character',
            name='equipment',
            field=models.TextField(blank=True, verbose_name='Ausrüstung'),
        ),
        migrations.AlterField(
            model_name='character',
            name='experience',
            field=models.IntegerField(default=0, verbose_name='Erfahrungspunkte'),
        ),
        migrations.AlterField(
            model_name='character',
            name='flaws',
            field=models.TextField(blank=True, verbose_name='Makel'),
        ),
        migrations.AlterField(
            model_name='character',
            name='gold',
            field=models.IntegerField(default=0, verbose_name='Gold'),
        ),
        migrations.AlterField(
            model_name='character',
            name='hit_dice',
            field=models.CharField(default='1d10', max_length=20, verbose_name='Trefferwürfel'),
        ),
        migrations.AlterField(
            model_name='character',
            name='hit_dice_total',
            field=models.IntegerField(default=1, verbose_name='Trefferwürfel gesamt'),
        ),
        migrations.AlterField(
            model_name='character',
            name='ideals',
            field=models.TextField(blank=True, verbose_name='Ideale'),
        ),
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='character_images/', verbose_name='Charakterbild'),
        ),
        migrations.AlterField(
            model_name='character',
            name='intelligence',
            field=models.IntegerField(default=10, verbose_name='Intelligenz'),
        ),
        migrations.AlterField(
            model_name='character',
            name='inventory',
            field=models.JSONField(blank=True, default=list, verbose_name='Inventar'),
        ),
        migrations.AlterField(
            model_name='character',
            name='level',
            field=models.IntegerField(default=1, verbose_name='Stufe'),
        ),
        migrations.AlterField(
            model_name='character',
            name='max_experience',
            field=models.IntegerField(default=10000, verbose_name='EP für nächste Stufe'),
        ),
        migrations.AlterField(
            model_name='character',
            name='max_hp',
            field=models.IntegerField(default=10, verbose_name='Maximale Trefferpunkte'),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='character',
            name='personality_traits',
            field=models.TextField(blank=True, verbose_name='Persönlichkeitsmerkmale'),
        ),
        migrations.AlterField(
            model_name='character',
            name='proficiencies',
            field=models.JSONField(blank=True, default=list, verbose_name='Übungen'),
        ),
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.CharField(max_length=100, verbose_name='Volk'),
        ),
        migrations.AlterField(
            model_name='character',
            name='silver',
            field=models.IntegerField(default=0, verbose_name='Silber'),
        ),
        migrations.AlterField(
            model_name='character',
            name='speed',
            field=models.IntegerField(default=30, verbose_name='Bewegung'),
        ),
        migrations.AlterField(
            model_name='character',
            name='spell_slots',
            field=models.JSONField(blank=True, default=dict, verbose_name='Zauberplätze'),
        ),
        migrations.AlterField(
            model_name='character',
            name='strength',
            field=models.IntegerField(default=10, verbose_name='Stärke'),
        ),
        migrations.AlterField(
            model_name='character',
            name='subclass',
            field=models.CharField(blank=True, max_length=100, verbose_name='Unterklasse'),
        ),
        migrations.AlterField(
            model_name='character',
            name='temp_hp',
            field=models.IntegerField(default=0, verbose_name='Temporäre Trefferpunkte'),
        ),
        migrations.AlterField(
            model_name='character',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='character',
            name='weapons',
            field=models.JSONField(blank=True, default=list, verbose_name='Waffen'),
        ),
        migrations.AlterField(
            model_name='character',
            name='wisdom',
            field=models.IntegerField(default=10, verbose_name='Weisheit'),
        ),
    ]
