# Generated by Django 5.2.11 on 2026-03-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_alter_character_options_character_feats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='known_spells',
            field=models.JSONField(blank=True, default=list, verbose_name='Bekannte Zauber'),
        ),
    ]
