# Generated by Django 5.2.11 on 2026-03-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_add_known_spells'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='abstammung',
            field=models.CharField(blank=True, max_length=100, verbose_name='Abstammung'),
        ),
        migrations.AddField(
            model_name='character',
            name='tool_proficiencies',
            field=models.JSONField(blank=True, default=list, verbose_name='Werkzeug-Übungen'),
        ),
        migrations.AlterField(
            model_name='character',
            name='alignment',
            field=models.CharField(blank=True, max_length=50, verbose_name='Gesinnung'),
        ),
        migrations.AlterField(
            model_name='character',
            name='speed',
            field=models.FloatField(default=9.0, verbose_name='Bewegung (m)'),
        ),
    ]
